// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"database/sql"
	"encoding/json"
)

type City struct {
	ID        int32
	City      sql.NullString
	Latitude  float64
	Longitude float64
	Country   sql.NullString
}

type Forecast struct {
	ID          int32
	CityID      int32
	Date        int64
	Temperature float64
	Weather     json.RawMessage
}
